site_name: User Guide
nav:
    - Welcome: index.md
    - What is Statit?: what_is.md
    - 'Getting started':
      - Web: gs/web.md
      - Excel: gs/excel.md
      - REST API: gs/api_rest.md
    - Reference:
      - Web: reference/web.md
      - Excel: reference/excel.md
      - REST API: reference/api_rest.md
theme:
  name: material
  palette:
    primary: white
    secondary: black
    accent: orange
  logo: img/logo_statit_64.png
  favicon: img/favicon.ico
extra_css:
  - stylesheets/extra.css
